NovelWeb/Controllers/AuthenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NovelLibrary.DataAccess;
using NovelLibrary.DataAccess.DTO;

namespace NovelWeb.Controllers
{
    public class AuthenController : Controller
    {
        ProjectLnContext context = new ProjectLnContext();

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(User loginUser)
        {
            if (loginUser != null)
            {
                string username = loginUser.Username;
                string password = EncryptPassword(loginUser.Password);
                var user = await context.Users.Where(u => u.Username.Equals(username) && u.Password.Equals(password)).FirstOrDefaultAsync();
                if (user != null)
                {
                    if (user.Status == false)
                    {
                        ViewBag.ErrorMessage = "Your account has been ban!";
                    }
                    else
                    {
                        HttpContext.Session.SetInt32("UserId", user.Id);
                        HttpContext.Session.SetInt32("isLogin", 1);
                        return RedirectToAction("Index", "Novels", new { area = "" });
                    }

                }
                else
                {
                    ViewBag.ErrorMessage = "Username or password invalid!";
                }
            }
            else
            {
                return View();
            }
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserDTO user)
        {
            if (ModelState.IsValid)
            {
                if (user != null)
                {
                    var checkExistUser = context.Users.Where(cu => cu.Username.Equals(user.UserName)).FirstOrDefault();
                    if (checkExistUser == null)
                    {
                        if (user.Images == null || user.Images.Count > 1)
                        {
                            ViewBag.ErrorMessage = "Register failed!";
                            return View();
                        }
                        else
                        {
                            if (user.Password.Equals(user.RePassword))
                            {

                                User newUser = new User
                                {
                                    Username = user.UserName,
                                    Password = EncryptPassword(user.Password),
                                    Role = false,
                                    Status = true,
                                    Avatar = ConvertToBytes(user.Images.ElementAt(0))
                                };
                                try
                                {
                                    context.Users.Add(newUser);
                                    await context.SaveChangesAsync();
                                    return RedirectToAction("Login");
                                }
                                catch (Exception ex)
                                {
                                    ViewBag.ErrorMessage = "Register failed!";
                                    return View();
                                }
                            }
                            else
                            {
                                return View();
                            }
                        }

                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Register failed!";
                        return View();
                    }
                } else
                {
                    ViewBag.ErrorMessage = "Register failed!";
                    return View();
                }
            }
            else
            {
                return View();
            }

        }

        private byte[] ConvertToBytes(IFormFile file)
        {
            Stream stream = file.OpenReadStream();
            using (var memoryStream = new MemoryStream())
            {
                stream.CopyTo(memoryStream);
                return memoryStream.ToArray();
            }
        }

        private string EncryptPassword(string password)
        {
            string result = "";
            try
            {
                byte[] enCryptByte = new byte[password.Length];
                enCryptByte = System.Text.Encoding.UTF8.GetBytes(password);
                result = Convert.ToBase64String(enCryptByte);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return result;
        }
    }
}

NovelWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NovelWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NovelWeb.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NovelWeb/Views/Shared/_LayoutNovel.cshtml
@using Microsoft.AspNetCore.Http
@using NovelLibrary.DataAccess
@inject IHttpContextAccessor HttpContextAccessor
@{
    int isLogin = (HttpContextAccessor.HttpContext.Session.GetInt32("isLogin") ?? 0);
    int id = (HttpContextAccessor.HttpContext.Session.GetInt32("UserId") ?? 0);
    User user = new User();
    if (id != 0)
    {
        ProjectLnContext context = new ProjectLnContext();
        user = context.Users.Where(u => u.Id == id).FirstOrDefault();
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet" />
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css"
          rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/6039db1001.js"
            crossorigin="anonymous"></script>
    <title>NIT Novels</title>
    <script>
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
    <style>
        .dropbtn {
            border: none;
            cursor: pointer;
        }

            .dropbtn:hover, .dropbtn:focus {
            }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f1f1f1;
            min-width: 160px;
            overflow: auto;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

        .dropdown a:hover {
            background-color: #ddd;
        }

        .show {
            display: block;
        }
    </style>
</head>
<body style="overflow-x: hidden">
    <header>
        <nav class="navbar navbar-light bg-dark">
            <div style="z-index:1" class="container-fluid justify-content-between p-2">
                <div class="d-flex flex-row align-items-center">
                    <img src="../images/StorePicture.png"
                         alt="Girl in a jacket"
                         style="border-radius: 50%; box-shadow: 0 0 50px #ccc"
                         width="100px"
                         height="100px" />
                    <a class="ps-2 text-white" href="@Url.Action("Index","Novels")" style="font-size: 25px; text-decoration: none">NIT Novels</a>
                </div>
                <div class="w-50">
                    <form class="d-flex input-group w-auto" action="/Novels/Index" method="Post">
                        <input type="search"
                               class="form-control rounded"
                               placeholder="Search"
                               aria-label="Search"
                               aria-describedby="search-addon"
                               id="searchText"
                               name="searchText" />
                        <input type="submit" class="input-group-text border-0" id="search-addon" value="Search">
                        </input>
                    </form>
                </div>
                <div>

                    @if (isLogin == 1)
                    {
                        <span>
                            <img src="data:image;base64,@System.Convert.ToBase64String(user.Avatar)
                             alt="Avatar"
                             style="border-radius: 50%; box-shadow: 0 0 50px #ccc"
                             width="50px"
                             height="50px"
                             onclick="myFunction()"
                             class="dropbtn" />
                        </span>
                        <div style="z-index:0" id="myDropdown" class="dropdown-content">
                            @*<a href="@Url.Action("UserProfile","Users")">Profile</a>*@
                            <a href="@Url.Action("Logout","Authen")">Logout</a>
                        </div>
                        <a class="text-white" style="text-decoration: none">Hi! @user.Username</a>
                    }
                    else
                    {
                        <span>
                            <img src="https://cdn3.iconfinder.com/data/icons/vector-icons-6/96/256-512.png"
                             alt="Avatar"
                             style="border-radius: 50%; box-shadow: 0 0 50px #ccc"
                             width="50px"
                             height="50px"
                             onclick="myFunction()"
                             class="dropbtn" />
                        </span>
                        <a class="text-white" style="text-decoration: none">Hello! Guest</a>
                        <div style="z-index:0" id="myDropdown" class="dropdown-content">
                            <a href="@Url.Action("Login","Authen")">Login</a>
                        </div>
                    }
                </div>
            </div>
        </nav>
       
        @if (ViewBag.CategoryList != null)
        {
            <div class="container-fluid w-100 m-3 justify-content-center text-center">
                <div class="container mt-3">
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <label for="category"
                               class="form-label"
                               style="
                              text-decoration: none;
                              font-size: large;
                              color: black;
                              font-weight: bold;
                            ">Category</label>
                            <select class="form-select" id="category" aria-label="Category" onchange="location = this.value;">
                                <option value="/Novels/Index"></option>
                                <option value="/Novels/Index">All</option>

                                @foreach (var item in ViewBag.CategoryList)
                                {
                                    <option value="/Novels/Index?categoryId=@item.Id">@item.Name</option>
                                }

                                <option value="/Novels/Index"></option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        }
    </header>
    @RenderBody()
</body>
</html>