NovelWeb/Controllers/ChapterController.cs
using Microsoft.AspNetCore.Mvc;
using NovelLibrary.DataAccess;

namespace NovelWeb.Controllers
{
    public class ChapterController : Controller
    {
        ProjectLnContext context = new ProjectLnContext();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ReadChapter(int id, int? index)
        {
            
            var currentChapter = context.Chapters.Where(c => c.Id == id).FirstOrDefault();
            int countIndex = context.Chapters.Where(c => c.NovelId == currentChapter.NovelId).ToList().Count;
            ViewBag.CountIndex = countIndex;
            if (index != null)
            {
                var currentNovel = context.Novels.Where(ln => ln.Id == currentChapter.NovelId).FirstOrDefault();
                currentChapter = context.Chapters.Where(c => c.NovelId == currentNovel.Id && c.Indexs == index).FirstOrDefault();
            } 
            var chapterImg = context.ChapterImages.Where(c => c.ChapterId == id).FirstOrDefault();
            var img = context.Images.Where(i => i.Id == chapterImg.ImageId).FirstOrDefault();
            ViewBag.Image = img;
            return View(currentChapter);
        }
    }
}

NovelWeb/Controllers/NovelsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NovelLibrary.DataAccess;
using NovelLibrary.DataAccess.DTO;

namespace NovelWeb.Controllers
{
    public class NovelsController : Controller
    {
        ProjectLnContext context = new ProjectLnContext();
        // GET: NovelsController
        public ActionResult Index(int? categoryId, string? searchText)
        {

            List<Novel> listNovel;
            if (categoryId == null)
            {
                listNovel = context.Novels.Where(ln => ln.Status == true).ToList();
            }
            else
            {
                listNovel = context.Novels.Where(ln => ln.Status == true && ln.CategoryId == categoryId).ToList();
            }
            if (searchText != null && searchText.Trim().Length > 0)
            {
                listNovel = context.Novels.Where(ln => ln.Status == true && ln.Name.ToLower().Contains(searchText.ToLower())).ToList();
            }

            var listCategories = context.Categories.ToList();
            List<NovelShowDTO> lsResult = new List<NovelShowDTO>();
            foreach (var item in listNovel)
            {
                var NovelImg = context.NovelImages.Where(n => n.NovelId == item.Id).FirstOrDefault();
                var img = context.Images.Where(i => i.Id == NovelImg.ImageId).FirstOrDefault();
                NovelShowDTO temp = new NovelShowDTO
                {
                    Id = item.Id,
                    Author = item.Author,
                    Name = item.Name,
                    CategoryId = item.CategoryId,
                    CategoryName = context.Categories.Where(c => c.Id == item.CategoryId).FirstOrDefault().Name,
                    Descripton = item.Descripton,
                    ImageData = img.ImageData
                };
                lsResult.Add(temp);
            }
            ViewBag.CategoryList = listCategories;
            return View(lsResult);
        }

        [HttpPost]
        public ActionResult Index(string searchText)
        {

            return RedirectToAction("Index", new { searchText = searchText });
        }

        // GET: NovelsController/Details/5
        public ActionResult Details(int id)
        {
            var novel = context.Novels.Where(n => n.Id == id).FirstOrDefault();
            var NovelImg = context.NovelImages.Where(n => n.NovelId == novel.Id).FirstOrDefault();
            var img = context.Images.Where(i => i.Id == NovelImg.ImageId).FirstOrDefault();
            ViewBag.CoverImg = img;
            var lsChapter = context.Chapters.Where(c => c.NovelId == novel.Id).ToList();
            ViewBag.ChapterList = lsChapter;
            ViewBag.CategoryName = context.Categories.Where(c => c.Id == novel.CategoryId).FirstOrDefault().Name;
            var NovelComment = context.NovelComments.Where(c => c.NovelId == id).ToList();
            List<UserCommentDTO> lsComment = new List<UserCommentDTO>();
            if(NovelComment.Count > 0)
            {
                foreach (var item in NovelComment)
                {
                    int userId = item.UserId;
                    var userCmt = context.Users.Where(u => u.Id == userId).FirstOrDefault();
                    UserCommentDTO temp = new UserCommentDTO
                    {
                        Avatar = userCmt.Avatar,
                        UserName = userCmt.Username,
                        Comments = item.Contents,
                        Date = item.Date
                    };
                    lsComment.Add(temp);
                }
            }
            ViewBag.CommentList = lsComment;
            return View(novel);
        }

        [HttpPost]
        public ActionResult CommentNovel(string comment, int userId, int novelId)
        {
            NovelComment newCmt = new NovelComment
            {
                UserId = userId,
                Contents = comment,
                NovelId = novelId,
                Date = DateTime.Now
            };
            context.NovelComments.Add(newCmt);
            context.SaveChanges();
            return RedirectToAction("Details", new { id = novelId });
        }

        // GET: NovelsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NovelsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NovelsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NovelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NovelsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NovelsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NovelWeb/Views/Novels/Details.cshtml
@using NovelLibrary.DataAccess
@model NovelLibrary.DataAccess.Novel
@inject IHttpContextAccessor HttpContextAccessor
@{
    int isLogin = (HttpContextAccessor.HttpContext.Session.GetInt32("isLogin") ?? 0);
    int id = (HttpContextAccessor.HttpContext.Session.GetInt32("UserId") ?? 0);
    User user = new User();
    if (id != 0)
    {
        ProjectLnContext context = new ProjectLnContext();
        user = context.Users.Where(u => u.Id == id).FirstOrDefault();
    }
}
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutNovel.cshtml";
}
<div class="container">
    <div class="d-flex">
        <div class="w-50">
            <div class="container">
                <h1>Novels Detail</h1>
                <div id="carouselExampleControls"
                     class="carousel slide text-center"
                     data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">

                            <img class="d-block w-100" src="data:image;base64,@System.Convert.ToBase64String(@ViewBag.CoverImg.ImageData)" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-50">
            <div class="m-5">
                <div>
                    <h1>@Model.Name</h1>
                    <h3>Author: @Model.Author</h3>
                    <h4>Desription:</h4>
                    <p>@Model.Descripton</p>
                    <h4>Category:</h4>
                    <p>@ViewBag.CategoryName</p>
                </div>
            </div>
        </div>
    </div>
    <div>
        <h4>Chapter list</h4>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Index
                    </th>
                    <th>
                        Chapter Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.ChapterList)
                {
                    <tr>
                        <td>
                            @item.Indexs
                        </td>
                        <td>
                            <a class="text-decoration: non" href="@Url.Action("ReadChapter","Chapter", new{id = @item.Id})" style="font-size: 25px; text-decoration: none">
                                @item.Name
                            </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div>
        @if(isLogin != 0) {
            <h4>Comment for Novel:</h4>
            <form class="d-flex input-group w-auto" action="/Novels/CommentNovel" method="Post">
                <input type="search"
                   class="form-control rounded"
                   placeholder="Your comment"
                   aria-label="Search"
                   aria-describedby="search-addon"
                   id="comment"
                   name="comment" />
                <input id="userId" name="userId" value="@user.Id" hidden>
                <input id="novelId" name="novelId" value="@Model.Id" hidden>
                <input type="submit" class="input-group-text border-0" id="search-addon" value="Submit comment">
            </form>
        }
    </div>
    <div>
        <h4>Chapter comments</h4>
        <hr />
        @if (ViewBag.CommentList.Count > 0) {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Avatar
                        </th>
                        <th>
                            Username
                        </th>
                        <th colspan="4">
                            Comment
                        </th>
                        <th>
                            Date
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.CommentList)
                    {
                        <tr>
                            <td>
                                <span>
                                    <img src="data:image;base64,@System.Convert.ToBase64String(item.Avatar)
                                 alt="Avatar"
                                 style="border-radius: 50%; box-shadow: 0 0 50px #ccc"
                                 width="50px"
                                 height="50px" />
                                </span>
                            </td>
                            <td>
                                @item.UserName
                            </td>
                            <td colspan="4">
                                @item.Comments
                            </td>
                            <td>
                                @item.Date
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

NovelWeb/Views/Novels/Index.cshtml
@model List<NovelLibrary.DataAccess.DTO.NovelShowDTO>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutNovel.cshtml";
}

<section style="background-color: #eee">
    <h1 class="p-3">List Novels</h1>
    <div class="container py-5">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-12 col-lg-4 mb-4 mb-lg-0">
                    <div class="card text-black">
                        <img src="data:image;base64,@System.Convert.ToBase64String(item.ImageData)"
                         class="card-img-top"
                         alt="Product Image" />
                        <div class="card-body">
                            <div class="text-center mt-1">
                                <h4 class="card-title">@item.Name</h4>
                            </div>
                            <div class="d-flex flex-row">
                                <button type="button"
                                    class="btn btn-primary flex-fill me-1"
                                    data-mdb-ripple-color="dark"
                                    onclick="window.location.href='@Url.Action("Details","Novels", new { id = @item.Id})'">
                                    Read Online
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>